# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxmpimpich
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxmpiopenmpi
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hmFeIZjn1wMeML522P09m0U2Fv/j+LR58E+l0r5Jn6yVQNKErOtzdRnr8/4ztWE7XuPXb6iV+4dePOqng6zJPFFsV7ejz5vzGIMA1EaMayQrbUjFAvWYkj9ZHnnZaZDs6q1flJeXuhc59F9hq6Hwtn4LDGuUZs3BG0cWldLk/Frfah2qwbSBUJwg5vzX4kG11rfpgVlMNg0Fit85HbySklKSAog4vZgA5hzxnagHrzM3Q/g56l/2zDqkp9DmeWvAU5tuTBuQsid0RmRfu/KTuCUC3mVtcsacIFdIgZgrPqwIdk+HWM3p0ErLNnNyVEA1sqv5NEElPpVT4pNAsx4YBgV48+jil+Yr6Dz68ZReu+rbDe43bc0GwUyfKy7z3/cEj7QpZdb3O8NmZyjI5at0mAz/noG9A+etgyA2myxNJvAxaFi5Bw3UTTTOJYRjgpjMP4ZU2u4jhQKlsHFH8uPQ/u7cjB12Lv+QBxXet6nzCBEjq6iHnQVEFJbVxGMQ8eZAGFxzq6W8qvaIU0JPqOxl15gBWNNvklyfASuEquKWUPw9OaetEJK9reLT4dvn5JJCm1jqXEPIVLipS4Og/PnwaxkBZqaKaKIJhJYi7h6JrbZphuH7Zn5R9rrodj4UfSMy8f0U3kzQIZr8JiG4CfSOF7ovF68H2UnvLLRMqtqg0pY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
