travis:
  secure:
    BINSTAR_TOKEN: h6LuN84RJGbZQV3frjYCSeUiD6hbDOukrr6mzZLuQ+fCnux15R9tD/PoS+M/TqJ/fKxyH6dHbpBOYSBYltddYnDEeRKd0VnSu2xEz/PLcOXnKb8pJUqZSMoylBIeiC3jhzBb+7TKciD1e7We3r+bbc7gaE5ebSa+Vv3TxeDBlk/CR9p1FawlecQB4mEEjb40ya6NmbbEyFuWUCUUAXktvck6uhHVlsgLS28S4xQ5OeWYRIsV8fD9DJJQK8glOzQftESsCGYP6mXUBXU+NnWYAZqbLZPqUKdrOQxT4YIlkwwg4caiy4W7trjjXwKKjSpV+F7fwVFDj2mdrxd2d5qtv3WxxYMTX/1fcEIHfMZyY1JKawYNKvR5iWH3zexR/W3Doghl81odWUBIu89i2GJ/lB7poi8kt9KILyB+lG3q7s87byXqLUVW3hvt26iB8Q3vHL6yz8/bS0RkInMylwC818lCUdKkD5CYN8/AVOvStc8aGJwlY6bBc2KN7B/q0u78W7tCxQibxYp5QUGbNeQ5Q4PcqZNRZsor3vgouAFH6Fq7+2jjYmrQJPUL2tsZi/WJslezA+d10RGrALwtFHJ8wdQm5i1SYhVAr6II6BI0RDfTcEgzv4S0hXKolUiAxeIRMGuwgiG1lYGJaGip/purCFNy/vSwcFLrakOyV4p1b5M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
